//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Globalization;

namespace Sensorium.Properties
{
	///	<summary>
	///	Provides access to string resources.
	///	</summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("netfx-System.Strings", "1.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	static partial class Strings
	{
		///	<summary>
		///	Provides access to string resources.
		///	</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("netfx-System.Strings", "1.0.0.0")]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public static partial class Brain
		{
			/// <summary>
			/// Looks up a localized string similar to: 
			///	Built action: {then}
			///	{action}
			/// </summary>
			public static string BuiltBehaviorAction(object then, object action)
			{
				return Resources.Brain_BuiltBehaviorAction.FormatWith(new 
				{
					then = then,
					action = action,
				});
			}
		
			/// <summary>
			/// Looks up a localized string similar to: 
			///	Built query: {when}
			///	{query}
			/// </summary>
			public static string BuiltBehaviorQuery(object when, object query)
			{
				return Resources.Brain_BuiltBehaviorQuery.FormatWith(new 
				{
					when = when,
					query = query,
				});
			}
		
			/// <summary>
			/// Looks up a localized string similar to: 
			///	Built state query: {when}
			///	{query}
			/// </summary>
			public static string BuiltStateQuery(object when, object query)
			{
				return Resources.Brain_BuiltStateQuery.FormatWith(new 
				{
					when = when,
					query = query,
				});
			}
		
			/// <summary>
			/// Looks up a localized string similar to: 
			///	Configuring behavior: {behavior}
			/// </summary>
			public static string ConfiguringBehavior(object behavior)
			{
				return Resources.Brain_ConfiguringBehavior.FormatWith(new 
				{
					behavior = behavior,
				});
			}
		
			/// <summary>
			/// Looks up a localized string similar to: 
			///	Executing behavior action: {behavior}
			/// </summary>
			public static string ExecutingBehaviorAction(object behavior)
			{
				return Resources.Brain_ExecutingBehaviorAction.FormatWith(new 
				{
					behavior = behavior,
				});
			}
		
			/// <summary>
			/// Looks up a localized string similar to: 
			///	Event stream matched behavior condition: {behavior}
			/// </summary>
			public static string MatchedBehaviorCondition(object behavior)
			{
				return Resources.Brain_MatchedBehaviorCondition.FormatWith(new 
				{
					behavior = behavior,
				});
			}
		
			/// <summary>
			/// Looks up a localized string similar to: 
			///	Topic '{topic}' in specified behavior '{behavior}' does not have a registered known type.
			/// </summary>
			public static string UnknonwnBehaviorTopic(object topic, object behavior)
			{
				return Resources.Brain_UnknonwnBehaviorTopic.FormatWith(new 
				{
					topic = topic,
					behavior = behavior,
				});
			}
		}
		
		///	<summary>
		///	Provides access to string resources.
		///	</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("netfx-System.Strings", "1.0.0.0")]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public static partial class CommandExtensions
		{
			/// <summary>
			/// Looks up a localized string similar to: 
			///	Cannot convert command with payload of type '{payload}' to a device action. Supported types are: boolean, number, string and void.
			/// </summary>
			public static string CannotConvertToDo(object payload)
			{
				return Resources.CommandExtensions_CannotConvertToDo.FormatWith(new 
				{
					payload = payload,
				});
			}
		}
	}
}

